### ISSUE TITLE
Ran into 2 issues...

### ISSUE THREAD

**Issue by canDry** [sinusphi/venvipy#12]
1st:  Missing dataclasses
```

Traceback (most recent call last):
  File "/home/xyz/.local/bin/venvipy", line 7, in <module>
    from venvipy.venvi import main
  File "/home/xyz/.local/lib/python3.6/site-packages/venvipy/venvi.py", line 49, in <module>
    import get_data
  File "/home/xyz/.local/lib/python3.6/site-packages/venvipy/get_data.py", line 11, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

```
Installed dataclasses and tried again...
2nd: error in get_data

```
Traceback (most recent call last):
  File "/home/xyz/.local/bin/venvipy", line 11, in <module>
    sys.exit(main())
  File "/home/xyz/.local/lib/python3.6/site-packages/venvipy/venvi.py", line 644, in main
    get_data.get_python_installs(True)
  File "/home/xyz/.local/lib/python3.6/site-packages/venvipy/get_data.py", line 104, in get_python_installs
    python_version = get_python_version(python_path)
  File "/home/xyz/.local/lib/python3.6/site-packages/venvipy/get_data.py", line 74, in get_python_version
    text="utf-8"
TypeError: __init__() got an unexpected keyword argument 'text'
QThread: Destroyed while thread is still running
Aborted (core dumped)

```
Gave up!   p.s. venvipy is great concept though!

**Comment by canDry** [comment]
Bump!

**Comment by sinusphi** [comment]
> 
> 
> 1st: Missing dataclasses
> 
> ```
> 
> Traceback (most recent call last):
>   File "/home/xyz/.local/bin/venvipy", line 7, in <module>
>     from venvipy.venvi import main
>   File "/home/xyz/.local/lib/python3.6/site-packages/venvipy/venvi.py", line 49, in <module>
>     import get_data
>   File "/home/xyz/.local/lib/python3.6/site-packages/venvipy/get_data.py", line 11, in <module>
>     from dataclasses import dataclass
> ModuleNotFoundError: No module named 'dataclasses'
> ```
> 
> Installed dataclasses and tried again...
> 2nd: error in get_data
> 
> ```
> Traceback (most recent call last):
>   File "/home/xyz/.local/bin/venvipy", line 11, in <module>
>     sys.exit(main())
>   File "/home/xyz/.local/lib/python3.6/site-packages/venvipy/venvi.py", line 644, in main
>     get_data.get_python_installs(True)
>   File "/home/xyz/.local/lib/python3.6/site-packages/venvipy/get_data.py", line 104, in get_python_installs
>     python_version = get_python_version(python_path)
>   File "/home/xyz/.local/lib/python3.6/site-packages/venvipy/get_data.py", line 74, in get_python_version
>     text="utf-8"
> TypeError: __init__() got an unexpected keyword argument 'text'
> QThread: Destroyed while thread is still running
> Aborted (core dumped)
> ```
> 
> Gave up! p.s. venvipy is great concept though!

Hi, 

I'm really sorry that I answer so late, COVID also messed up my life a bit. But now I have time to take care of this project again and would be happy if I can help you get VenviPy up and running.

Could you please provide some more information about your problem?

Which OS do you use?
What _exact_ Python version do you have (3.6.x) and _how was it installed_ (from Linux repos or did you build it from Source)?
If you built it from Source, what flags did you pass to `. / Configure`?

Everything so that I can reproduce the error. Thank you.

**Comment by canDry** [comment]
> COVID also messed up my life a bit  
  
Oh dear... **hope everything's ok**!?   
  
> Which OS do you use?  
Ubuntu 18LTS  
  
>What exact Python version?  
Python 3.6.9 and 2.7.17  
  
> How installed?  
via apt  
  
Did some digging and it seems that the Popen 'text' parameter **was added in 3.7** ... so that's probably the issue!  
  
Will try again when I get a chance in the next couple days and will let ya know!

**Comment by sinusphi** [comment]
Thank you for your answer. 

> > COVID also messed up my life a bit
>
> Oh dear... **hope everything's ok**!?

Yeah, everything's alright so far, thanks.  ;-)

> > Which OS do you use?
>
> Ubuntu 18LTS

Well, I remember I had trouble to test the build with Ubuntu and Python 3.6 on Travis. Unfortunately, that time I wasn't able to figure out what exactly the problem was and so I switched to testing the build with 3.7. 

> Did some digging and it seems that the Popen 'text' parameter **was added in 3.7** ... so that's probably the issue!

Agree. As you wrote I found this on [Python Docs](https://docs.python.org/3.7/library/subprocess.html#frequently-used-arguments)
> *New in version 3.7: Added the text parameter as an alias for universal_newlines.*

I'm pretty sure it should be the unrecognized `text` keyword in `subprocess.Popen()` which is an alias for the `universal_newlines` keyword. Thanks for investigating. 

Now, I think I'll replace the `text` keyword with `universal_newlines` and add the `dataclasses` module to the dependencies to keep VenviPy compatible with Python 3.6. Should be done this week. 

> Will try again when I get a chance in the next couple of days and will let ya know!

That would be great. Thank you very much for your contribution. I'll keep you posted.

**Comment by sinusphi** [comment]
I've just released a new version including the fixes I mentioned above  :wink: 
Now `setup.py` checks `sys.version` and installs the `dataclasses` module if necessary. 
Switched back to `universal_newlines` keyword in `subprocess.Popen`.
I hope you will be able to run VenviPy without errors. 

Make sure to install the latest release which is 0.2.17. 
You can check the version installed by running `venvipy --version`. 

Cheers

**Comment by sinusphi** [comment]
I think this issue can now be closed. Please contact me if you still have any problems.
